services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20021512
      POSTGRES_DB: dessert_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 5

  migrate:
    image: migrate/migrate:v4.15.2
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path=/migrations",
        "-database=postgres://postgres:20021512@db:5432/dessert_shop?sslmode=disable",
        "up"
      ]

  user-service:
    build:
      context: .
      dockerfile: microservices/user-service/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 20021512
      DB_NAME: dessert_shop
    ports:
      - "8081:8081"

  product-service:
    build:
      context: .
      dockerfile: microservices/product-service/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 20021512
      DB_NAME: dessert_shop
    ports:
      - "8082:8082"

volumes:
  postgres_data:
